# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Utility', [dirname(__file__)])
        except ImportError:
            import _Utility
            return _Utility
        if fp is not None:
            try:
                _mod = imp.load_module('_Utility', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Utility = swig_import_helper()
    del swig_import_helper
else:
    import _Utility
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def BeginMultiUndo() -> "void" :
  return _Utility.BeginMultiUndo()
BeginMultiUndo = _Utility.BeginMultiUndo

def EndMultiUndo() -> "void" :
  return _Utility.EndMultiUndo()
EndMultiUndo = _Utility.EndMultiUndo

def LoadDefault() -> "void" :
  return _Utility.LoadDefault()
LoadDefault = _Utility.LoadDefault

def Import(*args) -> "void" :
  return _Utility.Import(*args)
Import = _Utility.Import
# This file is compatible with both classic and new-style classes.


def LoadFromFile(*args) -> "bool" :
  return _Utility.LoadFromFile(*args)
LoadFromFile = _Utility.LoadFromFile

def SaveToFile(*args) -> "bool" :
  return _Utility.SaveToFile(*args)
SaveToFile = _Utility.SaveToFile

def ImportPointSeries(*args) -> "void" :
  return _Utility.ImportPointSeries(*args)
ImportPointSeries = _Utility.ImportPointSeries

