object Form16: TForm16
  Left = 306
  Top = 190
  HelpContext = 140
  BiDiMode = bdLeftToRight
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Insert shading'
  ClientHeight = 323
  ClientWidth = 342
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  ParentBiDiMode = False
  Position = poMainFormCenter
  ShowHint = True
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object PageControl1: TPageControl
    Left = 8
    Top = 16
    Width = 321
    Height = 257
    ActivePage = TabSheet1
    TabOrder = 0
    object TabSheet1: TTabSheet
      Caption = 'Shading'
      object Panel1: TPanel
        Left = 24
        Top = 14
        Width = 68
        Height = 68
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 0
        object Image1: TImage
          Left = 0
          Top = 0
          Width = 64
          Height = 64
          Hint = 'Shades the area between the function and the x-axis.'
          Picture.Data = {
            07544269746D617076080000424D760800000000000076000000280000004000
            000040000000010004000000000000080000130B0000130B0000100000001000
            000000000000000080000080000000808000800000008000800080800000C0C0
            C000808080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
            FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFF9
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFF99F
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFF99FFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFF9FAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFF99FFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFF99FFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFF9FAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFF99FFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFF99FFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFF99FAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFF9AFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFF99FFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFF99FAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFF9AFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFF99FFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCC99FAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC9AFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99CFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99FCCFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFCCFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            CCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            CCCCFFFAFFFAFFFAFFFAFFFAFF9FFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFF99FFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFA99FFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFF9FFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFF99FFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFA99FFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAF99FFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFF9FFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFA99FFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAF99FFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFF9FFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFA99FFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF}
          Stretch = True
          OnClick = ImageClick
        end
      end
      object Panel2: TPanel
        Left = 120
        Top = 14
        Width = 68
        Height = 68
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 2
        object Image2: TImage
          Left = 0
          Top = 0
          Width = 64
          Height = 64
          Hint = 'Shades the area below the function.'
          Picture.Data = {
            07544269746D617076080000424D760800000000000076000000280000004000
            000040000000010004000000000000080000230B0000230B0000100000001000
            000000000000000080000080000000808000800000008000800080800000C0C0
            C000808080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
            FF00FFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FF99AFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            99FFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAF9
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFF99F
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFF99FFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAF9FFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFF99FFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFF99FFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAF9FFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFF99FFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFF99FFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFA99FFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFF9FFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFF99FFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFA99FFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFF9FFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFF99FFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCA99FFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFC9FFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFF99CFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFA99FCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFF9FFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFCACCCACCCACCCACCCACCCACCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            CCCCCCACCCACCCACCCACCCACCCA99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            CCCCFFFAFFFAFFFAFFFAFFFAFF9FFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFF99FFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFA99FFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFF9FFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFF99FFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFA99FFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAF99FFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFF9FFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFA99FFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAF99FFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFF9FFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFA99FFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF}
          Stretch = True
          OnClick = ImageClick
        end
      end
      object Panel3: TPanel
        Left = 216
        Top = 14
        Width = 68
        Height = 68
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 4
        object Image3: TImage
          Left = 0
          Top = 0
          Width = 64
          Height = 64
          Hint = 'Shades the area above the function.'
          Picture.Data = {
            07544269746D617076080000424D760800000000000076000000280000004000
            000040000000010004000000000000080000430B0000430B0000100000001000
            000000000000000080000080000000808000800000008000800080800000C0C0
            C000808080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
            FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFF9
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFF99F
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFF99FFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFF9FAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFF99FFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFF99FFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFF9FAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFF99FFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFF99FFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFF99FAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFF9AFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFF99FFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFF99FAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFF9AFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFF99FFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCC99FAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC9AFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99CFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99FACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFF9AFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFCCCCCCCCCCCCCCCCCCCCCCCCC99CCACCCACCCACCCACCCACCCACCCACCCACC
            CACCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCACCCACCCACCCACCCACCCACCCACCCAC
            CCACFFFFFFFFFFFFFFFFFFFFFF9AFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFF99FFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFF99FAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFF9AFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFF99FFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFF99FAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFF99AFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFF99FAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFF99AFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFF9FFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFF99FAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFF99AFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFA9FFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFF}
          Stretch = True
          OnClick = ImageClick
        end
      end
      object Panel4: TPanel
        Left = 24
        Top = 120
        Width = 68
        Height = 68
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 6
        object Image4: TImage
          Left = 0
          Top = 0
          Width = 64
          Height = 64
          Hint = 'Shades the area between the function and the y-axis.'
          Picture.Data = {
            07544269746D617076080000424D760800000000000076000000280000004000
            000040000000010004000000000000080000430B0000430B0000100000001000
            000000000000000080000080000000808000800000008000800080800000C0C0
            C000808080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
            FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFAFFFAFFFAFFFAFFFAFFFAFFF
            99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCAFFFAFFFAFFFAFFFAFFFAFFFAF9
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFFFAFFFAFFFAFFFAFFFAFF99F
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFAFFFAFFFAFFFAFFFAFFF99FFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFAFFFAFFFAFFFAFFFAF9FFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFAFFFAFFFAFFFAFF99FFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFFFAFFFAFFFAFFF99FFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFAFFFAFFFAFFFAF9FFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFAFFFAFFFAFF99FFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCAFFFAFFFAFFF99FFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFFFAFFFA99FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFAFFFAFF9FFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFAFFF99FFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCAFFFA99FFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFAFF9FFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFF99FFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCC99FFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC9FFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99CFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF99FCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9AFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            CCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
            CCCCFFFFFFFFFFFFFFFFFFFFFF9AFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFF99FFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFF99FAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFF9AFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFF99FFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFF99FAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF99AFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFF99FAFFFAFFFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFF99AFFFAFFFAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFF9FFFAFFFAFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFF99FAFFFAFFFAFFFAFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFF99AFFFAFFFAFFFAFFFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF9FFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFACCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFAFFFAFFFAFFFAFFFAFFFAFFFAFFFAFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF}
          Stretch = True
          OnClick = ImageClick
        end
      end
      object Panel5: TPanel
        Left = 120
        Top = 120
        Width = 68
        Height = 68
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 8
        object Image5: TImage
          Left = 0
          Top = 0
          Width = 64
          Height = 64
          Hint = 'Shades the area inside the function.'
          Picture.Data = {
            07544269746D617076080000424D760800000000000076000000280000004000
            000040000000010004000000000000080000230B0000230B0000100000001000
            000000000000000080000080000000808000800000008000800080800000C0C0
            C000808080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
            FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            9FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            9FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFF9
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFF9
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFF9F
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFF9FA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFF9FF
            AFFFFFFFFFFFFFFFFFFF999FFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFF9AFF
            FAFFFFFFFFFFFFFFF9999FA99999FFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFF9FAF
            FFAFFFFFFFFFFFFFF9FAFFFAFFFA999FFFFCCFFFFFFFFFFFFFFFFFFFFFF9FFFA
            FFFAFFFFFFFFFFFF9FFFAFFFAFFFAFF999FCCFFFFFFFFFFFFFFFFFFFFF9FAFFF
            AFFFFFFFFFFFFFF99AFFFAFFFAFFFAFFFA99CFFFFFFFFFFFFFFFFFFFFF9FFAFF
            FAFFCCCCCCCCCCC9CCACCCACCCACCCACCCAC99CCCCCCCCCCCCCCCCCCC9ACCCAC
            CCACCCCCCCCCCCC9CCCACCCACCCACCCACCCACC999CCCCCCCCCCCCCCCC9CACCCA
            CCCAFFFFFFFFFFF9AFFFAFFFAFFFAFFFAFFCAFFFA99FFFFFFFFFFFFF9FFFAFFF
            AFFFFFFFFFFFFF9FFAFFFAFFFAFFFAFFFAFCCAFFFAF999FFFFFFFFF9FAFFFAFF
            FAFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACCFAFFFAFFF99FFFFFFF9FFAFFFAF
            FFAFFFFFFFFFFF9AFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFA99FFFF9AFFFAFFFA
            FFFAFFFFFFFFFF9FAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAF99F9FFAFFFAFFF
            AFFFFFFFFFFFFF9FFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFFAFF99FFFAFFFAFF
            FAFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAFFFA9FF99FFAFFFAF
            FFAFFFFFFFFFFF9AFFFAFFFAFFFAFFFAFFFACFFAFFFAFFFAFFF9FFFF99FAFFFA
            FFFAFFFFFFFFFF9FAFFFAFFFAFFFAFFFAFFCAFFFAFFFAFFFAF9FFFFFFF999FFF
            AFFFFFFFFFFFFF9FFAFFFAFFFAFFFAFFFAFCCAFFFAFFFAFFF9FFFFFFFFFFF99F
            FAFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACCFAFFFAFFFAF9FFFFFFFFFFFFFF9
            9FAFFFFFFFFFFF9AFFFAFFFAFFFAFFFAFFFACFFAFFFAFFF9FFFFFFFFFFFFFFFF
            F999FFFFFFFFFF9FAFFFAFFFAFFFAFFFAFFCAFFFAFFFAF9FFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFF9FFAFFFAFFFAFFFAFFFAFCCAFFFAFFF9FFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACCFAFFFAF9FFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFF9FFFFAFFFAFFFAFFFAFFFACFFAFFFA9FFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9AFFFAFFFAFFFAFFFAFFCAFFFAFF9FFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9FAFFFAFFFAFFFAFFFAFCCAFFFA9FFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9FFAFFFAFFFAFFFAFFFACCFAFF9FFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9FFFAFFFAFFFAFFFAFFFACFFA9FFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9AFFFAFFFAFFFAFFFAFFCAFF9FFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9FAFFFAFFFAFFFAFFFAFCCA9FFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF9FFAFFFAFFFAFFFAFFFACC9FFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF99FFAFFFAFFFAFFFAFFFC9FFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFF9FFFAFFFAFFFAFFFAF99CFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFF99FFAFFFAFFFAFF99FCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFF99FFAFFFAF9999FFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFF99999999FFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF}
          Stretch = True
          OnClick = ImageClick
        end
      end
      object Panel6: TPanel
        Left = 216
        Top = 120
        Width = 68
        Height = 68
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 10
        object Image6: TImage
          Left = 0
          Top = 0
          Width = 64
          Height = 64
          Hint = 
            'Shades the area between the main function and the function selec' +
            'ted in the list to the right.'
          Picture.Data = {
            07544269746D617076080000424D760800000000000076000000280000004000
            000040000000010004000000000000080000230B0000230B0000100000001000
            000000000000000080000080000000808000800000008000800080800000C0C0
            C000808080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
            FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            99FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFF9
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFF99F
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFF99FFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFF9FAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFF99FFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFF99FFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFF9FAFFFAFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFF99FFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFF99FFAFFFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFF99FAFFFAFFFAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFF9AFFFAFFFAFFFAFFFA
            FFFA9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFF99FFAFFFAFFFAFFFAFFF
            AFFFF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFF99FAFFFAFFFAFFFAFFFAFF
            FAFFFFA99FFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFF9AFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAF99FFFFFFFFFFFFFFFFFFFFFFFFCCFF99FFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFF99FFFFFFFFFFFFFFFFFFFFFFCC99FAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFF99FFFFFFFFFFFFFFFFFFFFC9AFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFA99FFFFFFFFFFFFFFFFF99CFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAF99FFFFFFFFFFFFF99FACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFAFF99FFFFFFFFFF9AFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFCACCCACCCACCCACCC99CCCCCC99CCACCCACCCACCCACCCACCCACCCACCCACC
            CACCCCACCCACCCACCCACCCC99CC99CACCCACCCACCCACCCACCCACCCACCCACCCAC
            CCACFFFAFFFAFFFAFFFAFFFAF99AFFFAFFFACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFAFFFAFFF99F99FFFAFFCAFFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAFFFAFFFA99FFFFF99FFAFCCAFFFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFFAFFFAFF9FFFFFFFFF99FACCFAFFFAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFAFFFAFFF99FFFFFFFFFFFF99ACFFAFFFAFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAFFFAFFFA99FFFFFFFFFFFFFFFF99FFFAFFFAFFFAFFFAFFFAFFFAFFF
            AFFFFAFFFAFFFAF99FFFFFFFFFFFFFFFFFFCC99FFAFFFAFFFAFFFAFFFAFFFAFF
            FAFFFFAFFFAFFF9FFFFFFFFFFFFFFFFFFFFCCFF99FAFFFAFFFAFFFAFFFAFFFAF
            FFAFFFFAFFFA99FFFFFFFFFFFFFFFFFFFFFCCFFFF99AFFFAFFFAFFFAFFFAFFFA
            FFFAAFFFAF99FFFFFFFFFFFFFFFFFFFFFFFCCFFFFFF99FFFAFFFAFFFAFFFAFFF
            AFFFFAFFF9FFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFF99FFAFFFAFFFAFFFAFF
            FAFFFFA99FFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFF99FAFFFAFFFAFFFAF
            FFAFF99FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFF99AFFFAFFFAFFFA
            FFFA9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFF99FFFAFFFAFFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFF99FFAFFFAFF
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFF99FAFFFAF
            FFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFF99AFFFA
            FFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFF99FFF
            AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFF99F
            FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFF9
            9FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            F99AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFF}
          Stretch = True
          OnClick = ImageClick
        end
      end
      object RadioButton3: TMyRadioButton
        Left = 208
        Top = 83
        Width = 97
        Height = 35
        Hint = 'Shades the area above the function.'
        Caption = 'Above function'
        TabOrder = 5
        MultiLine = True
      end
      object RadioButton1: TMyRadioButton
        Left = 3
        Top = 83
        Width = 108
        Height = 35
        Hint = 'Shades the area between the function and the x-axis.'
        Caption = 'Between function and x-axis'
        Checked = True
        TabOrder = 1
        TabStop = True
        MultiLine = True
      end
      object RadioButton6: TMyRadioButton
        Left = 208
        Top = 189
        Width = 89
        Height = 35
        Hint = 
          'Shades the area between the main function and the function selec' +
          'ted in the list to the right.'
        Caption = 'Between functions'
        TabOrder = 11
        MultiLine = True
        OnCheckedChange = RadioButton6CheckedChange
      end
      object RadioButton4: TMyRadioButton
        Left = 4
        Top = 189
        Width = 108
        Height = 35
        Hint = 'Shades the area between the function and the y-axis.'
        Caption = 'Between function and y-axis'
        TabOrder = 7
        MultiLine = True
      end
      object RadioButton5: TMyRadioButton
        Left = 112
        Top = 189
        Width = 89
        Height = 35
        Hint = 'Shades the area inside the function.'
        Caption = 'Inside function'
        TabOrder = 9
        MultiLine = True
      end
      object RadioButton2: TMyRadioButton
        Left = 112
        Top = 83
        Width = 95
        Height = 35
        Hint = 'Shades the area below the function.'
        Caption = 'Below function'
        TabOrder = 3
        MultiLine = True
      end
    end
    object TabSheet2: TTabSheet
      Caption = 'Options'
      ImageIndex = 1
      object Label12: TLabel
        Left = 8
        Top = 12
        Width = 56
        Height = 13
        Caption = 'Description:'
        FocusControl = Edit5
      end
      object GroupBox1: TGroupBox
        Left = 8
        Top = 32
        Width = 297
        Height = 89
        Caption = 'Range'
        TabOrder = 1
        object Label7: TLabel
          Left = 8
          Top = 56
          Width = 16
          Height = 13
          Caption = 'To:'
          FocusControl = Edit2
        end
        object Label6: TLabel
          Left = 8
          Top = 24
          Width = 26
          Height = 13
          Caption = 'From:'
          FocusControl = Edit1
        end
        object Edit1: TMyEdit
          Left = 48
          Top = 22
          Width = 77
          Height = 21
          Hint = 'Coordinate where the shading starts.'
          ImeMode = imHanguel
          TabOrder = 0
        end
        object Edit2: TMyEdit
          Left = 48
          Top = 54
          Width = 77
          Height = 21
          Hint = 'Coordinate where the shading ends.'
          TabOrder = 2
        end
        object CheckBox2: TCheckBox
          Left = 134
          Top = 56
          Width = 161
          Height = 17
          Hint = 'Check to increase the end coordinate until intersection.'
          Caption = 'Increase to intersection'
          TabOrder = 3
        end
        object CheckBox1: TCheckBox
          Left = 134
          Top = 24
          Width = 161
          Height = 17
          Hint = 'Check to decrease the start coordinate until intersection.'
          Caption = 'Decrease to intersection'
          TabOrder = 1
        end
      end
      object GroupBox3: TGroupBox
        Left = 8
        Top = 128
        Width = 297
        Height = 89
        Caption = 'Properties'
        TabOrder = 2
        object Label5: TLabel
          Left = 8
          Top = 56
          Width = 27
          Height = 13
          Caption = 'Color:'
          FocusControl = ExtColorBox1
        end
        object Label4: TLabel
          Left = 8
          Top = 24
          Width = 26
          Height = 13
          Caption = 'Style:'
          FocusControl = ShadeSelect1
        end
        object ShadeSelect1: TShadeSelect
          Left = 48
          Top = 20
          Width = 81
          Height = 22
          Hint = 'Select the style used for the shading.'
          TabOrder = 0
        end
        object ExtColorBox1: TExtColorBox
          Left = 48
          Top = 54
          Width = 81
          Height = 22
          Hint = 'Select color used for shading.'
          TabOrder = 2
          OnChange = ExtColorBox1Change
          AutoDroppedWidth = True
          Selected = clScrollBar
          DefaultName = 'Default'
          CustomName = 'Custom...'
        end
        object CheckBox5: TCheckBox
          Left = 134
          Top = 24
          Width = 161
          Height = 17
          Hint = 'Mark the border around the shading.'
          Caption = 'Mark border'
          Checked = True
          State = cbChecked
          TabOrder = 1
        end
      end
      object Edit5: TEdit
        Left = 72
        Top = 8
        Width = 233
        Height = 21
        Hint = 'Enter a description to show in the legend.'
        TabOrder = 0
      end
    end
    object TabSheet3: TTabSheet
      Caption = '2nd function'
      ImageIndex = 2
      object Label11: TLabel
        Left = 8
        Top = 8
        Width = 62
        Height = 13
        Caption = '2nd function:'
        FocusControl = ListBox1
      end
      object ListBox1: TListBox
        Left = 8
        Top = 24
        Width = 297
        Height = 89
        Hint = 
          'Select the second function when you want a shading between two f' +
          'unctions.'
        Enabled = False
        ItemHeight = 13
        TabOrder = 0
      end
      object GroupBox2: TGroupBox
        Left = 8
        Top = 128
        Width = 297
        Height = 89
        Caption = 'Shading range for 2nd function'
        TabOrder = 1
        object Label8: TLabel
          Left = 8
          Top = 24
          Width = 26
          Height = 13
          Caption = 'From:'
          FocusControl = Edit3
        end
        object Label9: TLabel
          Left = 8
          Top = 56
          Width = 16
          Height = 13
          Caption = 'To:'
          FocusControl = Edit4
        end
        object Edit3: TMyEdit
          Left = 48
          Top = 22
          Width = 77
          Height = 21
          Hint = 'Coordinate where the shading starts.'
          TabOrder = 0
        end
        object Edit4: TMyEdit
          Left = 48
          Top = 54
          Width = 77
          Height = 21
          Hint = 'Coordinate where the shading ends.'
          TabOrder = 2
        end
        object CheckBox4: TCheckBox
          Left = 134
          Top = 56
          Width = 161
          Height = 17
          Hint = 'Check to increase the end coordinate until intersection.'
          Caption = 'Increase to intersection'
          TabOrder = 3
        end
        object CheckBox3: TCheckBox
          Left = 134
          Top = 24
          Width = 161
          Height = 17
          Hint = 'Check to decrease the start coordinate until intersection.'
          Caption = 'Decrease to intersection'
          TabOrder = 1
        end
      end
    end
  end
  object Button1: TButton
    Left = 80
    Top = 288
    Width = 75
    Height = 25
    Caption = 'OK'
    Default = True
    TabOrder = 1
    OnClick = Button1Click
  end
  object Button2: TButton
    Left = 168
    Top = 288
    Width = 75
    Height = 25
    Cancel = True
    Caption = 'Cancel'
    ModalResult = 2
    TabOrder = 2
  end
  object Button3: TButton
    Left = 256
    Top = 288
    Width = 75
    Height = 25
    HelpType = htKeyword
    Caption = 'Help'
    TabOrder = 3
    OnClick = Button3Click
  end
end
